### PR TITLE
Add avy-menu interface

### PR DESCRIPTION
**Pull request by clemera**
Hi, I have added an [`avy-menu`](https://github.com/mrkkrp/avy-menu) interface.

### CODE REVIEW

**Comment by clemera** [comment]
Hm, do I need to make a new PR with signed commits? I would have to setup it first.

**Comment by clemera** [comment]
Ok, thanks!

**Comment by d12frosted** [comment]
Thank you very much! Looks really great and useful. Gonna use it a while 😸 

BTW, if you don't mind, listed you as an author of this interface. This is public information from your GitHub account. But let me know if you prefer to change that information.

**Comment by clemera** [comment]
Great! Thank you, too!

**Pull request merged**
