### PR TITLE
highlight word being currently corrected

### LINKED ISSUE #52: Highlight the word that is currently being corrected
First, thank you for this package! Perhaps it can be achieved by other means, but I was wondering if it would be possible to add a custom face that would highlight the word that is currently being corrected?

### PR DESCRIPTION
**Pull request by d12frosted**
Fixes #52

Co-authored-by: Daniel Hubmann <hubisan@gmail.com>

### CODE REVIEW

**Comment by hubisan** [comment]
Looks great and thx for your package btw.

Feedback (not fully tested):

### Remove `when-let`

Was just lazy using `when-let` (which should be `when-let*`, no idea why it works without the *). It's easy to go without to not force 25.1:

```elisp
(defun flyspell-correct-highlight ()
  "Highlight the spelling error at point."
  (setq flyspell-correct-overlay-window (selected-window))
  (let* ((ov (flyspell-correct--overlay-loc))
         (ov-start (car-safe ov))
         (ov-end (cdr-safe ov)))
    (when ov
      (flyspell-correct--highlight ov-start ov-end t))))
```

See below for more changes to this function in *Split highlight and remove-highlight*.

### `defcustom` to turn highlighting on/off

Using a `defcustom` set to `t` by default to be able to turn highlighting off:

```elisp
(defcustom flyspell-correct-highlight t
  "If non-nil highlight the word while correcting.
The face `flyspell-correct-highlight-face' is used for highlighting."
  :group 'flyspell
  :type 'boolean)
```

This of course needs to be taken into account in `flyspell-correct-at-point`:

```elisp
...
(when flyspell-correct-highlight 
   (flyspell-correct-highlight))
...
(when flyspell-correct-highlight 
  (flyspell-correct-highlight-remove)
```

### `defface` for the face

Better to use a dedicated face instead of a what ispell is doing, using a defvar:

```elisp
(defface flyspell-correct-highlight-face
  '((t (:inherit flyspell-duplicate)))
  "Face used for highlighting the word while correcting.")
```

One could be more aggressive so the users will notice the update by inheriting from another face like `isearch` :-)

### Split highlight and remove-highlight

I used those two functions together because of how ispell worked. But it probably makes it just more complicated. So when taken apart this become (which imo is more transparent):

```elisp
;; Using two -- to make clear that this is not a public function.
(defun flyspell-correct--highlight ()
  "Highlight the spelling error at point."
  (setq flyspell-correct-overlay-window (selected-window))
  (let* ((ov (flyspell-correct--overlay-loc))
         (ov-start (car-safe ov))
         (ov-end (cdr-safe ov)))
    (when ov
      (if flyspell-correct-overlay
          (move-overlay flyspell-correct-overlay ov-start ov-end (current-buffer))
        (setq flyspell-correct-overlay (make-overlay ov-start ov-end))
        (overlay-put flyspell-correct-overlay 'priority 1001)
        (overlay-put flyspell-correct-overlay 'face flyspell-correct-overlay-face)))))

;; Using two -- to make clear that this is not a public function.
(defun flyspell-correct--highlight-remove ()
  "Remove the spelling error highlights."
  (save-window-excursion
    (select-window flyspell-correct-overlay-window)
    (when flyspell-correct-overlay
      (delete-overlay flyspell-correct-overlay)
      (setq flyspell-correct-overlay nil))))
```

If changed you have to modify the function calls.

**Comment by hubisan** [comment]
Not sure if the `(select-window flyspell-correct-overlay-window)` is needed btw. 

If need it is probably a good idea to check if it is a window and if it is live with:
```elisp
(when (window-live-p flyspell-correct-overlay-window)
    ...
) 
```

**Comment by d12frosted** [comment]
@hubisan thank you very much for such detailed review! You can see the changes [here](https://github.com/d12frosted/flyspell-correct/compare/b985411cd2c33265cbd2beb3adb1b69886974e95..82ddc25f7a32e50f3f7b270702ceeace711ae4e8)

1. Also not sure why it works with `*`. And for some reason I thought that `(car nil)` errors out. 🤔 That's why didn't convert to plain old `let` + `when`. Thanks for pointing out! Restored support of some older versions of Emacs!
2. I though about making highlighting optional, but though that no one will need it.
2.1. I never used customization. What do you think about using `flyspell-correct` group? I see that `flyspell` has many options already.
2.2. Wow, I didn't know that you can have the same name for variable and for function. But I don't like it 😸 So will rename underlying functions.
3. Good point about `defface!`
4. Regarding the two dashes - good point. Already did in 2.2 :) Regarding total split - makes a lot of sense! 
5. Didn't know about `window-live-p`. But it seems that remembering the window is not needed as it just works with other completion backends. I though that it's needed for helm.

**Comment by hubisan** [comment]
Great additions. Tested it with Emacs 27 and avy-menu interface, worked flawless.

**About 1.**

Rather use `car-safe` and `cdr-safe` to be sure that it doesn't throw an error:

https://github.com/d12frosted/flyspell-correct/blob/26112ede89c9dff9f0670526a1336c6f8d3c9e26/flyspell-correct.el#L267-L271

```elisp
(let* ((ov (flyspell-correct--overlay-loc)) 
        (ov-start (car-safe ov)) 
        (ov-end (cdr-safe ov))) 
   (when ov 
     (if flyspell-correct-overlay 
```

```text
(car-safe OBJECT) Return the car of OBJECT if it is a cons cell, or else nil.
(cdr-safe OBJECT) Return the cdr of OBJECT if it is a cons cell, or else nil.
```

Looking forward to being able to ditch some custom code from my init :-)

**Comment by d12frosted** [comment]
Nice catch! Let it pass CI and will merge it!

**Comment by d12frosted** [comment]
Yay! Merged to master! Thank you very much for initial code and for the great review, @hubisan!

**Pull request merged**
